version: '3.8'
services:
  db:
    image: mysql:latest
    restart: always
    container_name: jornada-milhas
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: jornada_milhas
      TZ: America/Sao_Paulo
    ports:
      - 3306:3306
    volumes:
      - /var/lib/docker/volumes/jornada_milhas/_data